apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i1ckva5zi-go
  janus-idp.io/tekton: i1ckva5zi-go
  backstage.io/kubernetes-id: i1ckva5zi-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i1ckva5zi-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
