apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: i1ckva5zi-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: i1ckva5zi-go 
  name: i1ckva5zi-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: i1ckva5zi-go 
